name: CI Download BIDV Club Data
  
on:

  schedule:
    - cron: '0 4 * * *'
    - cron: '0 18 * * *'


jobs:
  Download_BIDVRun_TeamData:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Get Team Data Json
        run: |
          python DownloadData.py
          git config --global user.name 'trungmc'
          git config --global user.email 'trungmc@yahoo.com'
          git add .
          
          git commit --allow-empty -am "Update team data"
          git push 
          git status     
          

